version: "3.8"

services:
  self-driving-car:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: self-driving-car
    restart: always
    privileged: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=30  # Set a unique ROS 2 domain ID
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./workspace:/workspace  # Mount local workspace directory
    networks:
      - self-driving-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: ["/bin/bash"]

networks:
  self-driving-net:
    driver: bridge
